quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sg_user
quarkus.datasource.password=development

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

script.directory=/home/pi/Bookshelf/EnterpriseDevelopmentWithRPi/SourceCode/Chapter_5/smartgarden-quarkus/src/main/resources/scripts/
python.script.runner=/home/pi/Bookshelf/EnterpriseDevelopmentWithRPi/SourceCode/Chapter_5/smartgarden-quarkus/src/main/resources/scripts/run-python.sh
thp.python.script=thp_sensor.py

%prod.quarkus.datasource.devservices.show-logs=false
%prod.scheduler.enabled=true
%prod.scheduler.measurement-interval=60m
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/weather

%dev.scheduler.enabled=true
%dev.scheduler.measurement-interval=2m
%dev.quarkus.datasource.devservices.show-logs=true
%dev.quarkus.hibernate-orm.schema-management.strategy=create
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/weather

%test.scheduler.enabled=false
%test.scheduler.measurement-interval=2m
%test.quarkus.datasource.devservices.show-logs=true
%test.quarkus.datasource.devservices.init-script-path=import-test.sql