quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=collector
quarkus.datasource.password=development
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/collection

kafka.bootstrap.servers=localhost:9092 
mp.messaging.outgoing.collection-output.topic=collection-update