apiVersion: v1
kind: Service
metadata:
  name: {{ include "collection-chart.name" . }}
  labels:
    {{- include "collection-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "collection-chart.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP