####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/smartgarden-quarkus .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/smartgarden-quarkus
#
# The ` registry.access.redhat.com/ubi9/ubi-minimal:9.7` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/ubi8/ubi-minimal:8.10`.
###
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7

### Custom environment variable for the THP sensor URL
ENV THP_SENSOR_URL="http://172.17.0.1:8088"

### The host DB URL
ENV QUARKUS_DATASOURCE_REACTIVE_URL="vertx-reactive:postgresql://172.17.0.1:5432/weather"

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
