spring.application.name=CollectionApplication
server.port=8088

debug=false

spring.security.oauth2.resourceserver.jwt.jwkSetUri=https://${KEYCLOAK_HOST:localhost}:8443/realms/collection/protocol/openid-connect/certs

spring.r2dbc.username=collector
spring.r2dbc.password=${DB_PASS}
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:5432/collection
spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.password=${spring.r2dbc.password}
spring.flyway.user=${spring.r2dbc.username}
spring.flyway.url=jdbc:postgresql://${DB_HOST:localhost}:5432/collection
spring.flyway.default-schema=collection
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true

spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.consumer.group-id=group_id
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer-topic=collection-update
