spring.application.name=CollectionApplication
server.port=8888

# JWT Configuration
# Defines the resource ID that the JWT auth converter should validate against.
#jwt.auth.converter.resource-id=my-client
# Specifies the attribute in the JWT that contains the principal (user identifier).
#jwt.auth.converter.principal-attribute=principal_username
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8443/realms/collection
#spring.security.oauth2.resourceserver.jwt.jwkSetUri=https://localhost:8443/realms/collection/protocol/openid-connect/certs
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8443/realms/collection
spring.security.oauth2.resourceserver.jwt.jwkSetUri=https://localhost:8443/realms/collection/protocol/openid-connect/certs

#server.ssl.enabled=true
#server.port=8444
#server.ssl.trust-store=classpath:customcacerts
#server.ssl.trust-store-password=changeit
#server.ssl.trust-store-type=JKS

#server.ssl.key-store=classpath:collection.p12
#server.ssl.key-store-password=secret
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=my-cert
#spring.ssl.bundle.jks.keycloak.truststore.location=classpath:myTrustStore.jks
#spring.ssl.bundle.jks.keycloak.truststore.password=changeit

#spring.http.clients.ssl.bundle=keycloak

#server.ssl.client-auth=WANT